name: CI/CD Pipeline for tailWindCSS_MATC


on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

env:
 DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
 DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}   
 DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}

jobs:
 build:
   runs-on: ubuntu-latest


   steps:
   
     - name: Checkout repository
       uses: actions/checkout@v3


     - name: set up Docker
       uses: docker/setup-buildx-action@v3

     - name: login the docker, Build,Push the image
       run: |
          docker login -u ${{ secrets.DOCKER_USERNAME}} -p ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'$DOCKER_USERNAME", "password": "*$DOCKER_PASSWORD'"}' https://hub.docker.com/v2/kubendrapandian10d/my-project -r .token) 
          input_string=$(curl -s -H "Authorization: Bearer $DOCKER_TOKEN" https://registry.hub.docker.com/v2/repositories/kubendrapandian10d/my-project/tags | jq -r '.results | max_by(.last_updated) | .name')
          number=$(echo "$input_string" | grep -OE '[0-9]+$') && new_number=$((number + 1)) && new_string=$(echo "$input_string" | sed "s/$number$/$new_number/")
          docker build -t kubendrapandian/my-project:$new_string .
          docker push kubendrapandian10d/my-project:$new_string
