name: CI/CD Pipeline for tailWindCSS_MATC


on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

env:
 DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
 DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}   

jobs:
 build:
   runs-on: ubuntu-latest


   steps:
   
     - name: Checkout repository
       uses: actions/checkout@v3


     - name: Log in to DockerHub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
         DOCKER_ACCESS_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'$DOCKER_USERNAME", "password": "*$DOCKER_PASSWORD'"}' https://hub.docker.com/v2/users/login/jq -r .token) input_string=$(curl -s -H "Authorization: Bearer $DOCKER_ACCESS_TOKEN" https://registry.hub.docker.com/v2/repositories/decoders10/$DOW JONES/tags | jq -r '.results | max_by(.last_updated) | .name') number=$(echo "$input_string" | grep -OE '[0-9]+$') && new_number=$((number + 1)) && new_string=$(echo "$input_string" | sed "s/$number$/$new_number/")
27

     - name: Build Docker image
       run: docker build -t kubendrapandian10d/my-project:latest .
      
     - name: Push Docker image
       run: docker push kubendrapandian10d/my-project:latest 

     - name: Extract metadata (tags, labels) for Docker
       id: meta
       uses: docker/metadata-action@v4
       with:
          images: kubendrapandian10d/my-project
          
     - name: Build and push Docker image
       uses: docker/build-push-action@v4
       with:
         context: .
         push: true
         tags: kubendrapandian10d/my-project:latest
         labels: kubendrapandian10d/my-project:latest
        


