name: CI/CD Pipeline 

on:
 push:
   branches:
     - main
 pull_request:
   branches:
     - main

env:
 DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
 DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}   

jobs:
 build:
   runs-on: ubuntu-latest


   steps:
   
     - name: Checkout repository
       uses: actions/checkout@v3
      
     - name: set up Docker
       uses: docker/setup-buildx-action@v1

     - name: login the docker ,Build and push the Image  
       run: |
         docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
         DOCKER_ACCESS_TOKEN=$(curl -s -H "Content-Type: application/json" -X POST -d '{"username": "'$DOCKER_USERNAME'", "password": "'$DOCKER_PASSWORD'"}' https://hub.docker.com/v2/users/login/ | jq -r .token)
         input_string=$(curl -s -H "Authorization: Bearer $DOCKER_ACCESS_TOKEN" https://registry.hub.docker.com/v2/repositories/kubendrapandian10d/my-project/tags | jq -r '.results | max_by(.last_updated) | .name')
         number=$(echo "$input_string" | grep -oE '[0-9]+$') && new_number=$((number + 1)) && new_version=$(echo "$input_string" | sed "s/$number$/$new_number/")
         docker build -t kubendrapandian10d/my-project:$new_string
         docker push kubendrapandian10d/my-project:$new_string
