name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Determine Version
        id: version
        run: echo "::set-output name=version::v1.0.$(( $(git tag | wc -l) + 1 ))"

      - name: Build Docker image
        run: docker build -t kubendrapandian10d/my-project:${{ steps.version.outputs.version }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push kubendrapandian10d/my-project:${{ steps.version.outputs.version }}
