name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

     
      - name: determine version
        id: version
        run: |
          tag_count=$(git tag | wc -l)
          new_version="v1.0.$((tag_count + 1))"
          echo "Version: $new_version"
          echo "::set-output name=version::$new_version"

      - name: Use the new version
        run: echo "The new version is ${{ steps.generate-version.outputs.version }}"
      - name: Build Docker image
        run: docker build -t kubendrapandian10d/my-project:${{ steps.version.outputs.version }} .

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push kubendrapandian10d/my-project:${{ steps.version.outputs.version }}
